# Generated by Django 5.1.15 on 2026-06-09 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assist', '0001_initial'),
        ('assessments', '0001_initial'),
        ('findings', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='findings.finding'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='risk_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='assessments.riskitem'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['tenant', 'risk_item'], name='ai_assist_a_tenant__4bb851_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['tenant', 'finding'], name='ai_assist_a_tenant__89cc2b_idx'),
        ),
    ]
