# Generated by Django 5.1.15 on 2026-06-09 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assist', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(help_text='The AI feature helper identifier.', max_length=100)),
                ('prompt', models.TextField(help_text='The prompt template submitted to the LLM.')),
                ('response', models.TextField(help_text='The suggestion output returned by the LLM.')),
                ('model_used', models.CharField(help_text='Model used during completion.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'feature'], name='ai_assist_a_tenant__e722ff_idx'), models.Index(fields=['tenant', 'created_at'], name='ai_assist_a_tenant__996d9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('Gemini', 'Gemini'), ('OpenAI', 'OpenAI'), ('Ollama', 'Ollama')], default='Gemini', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='API key for Gemini/OpenAI', max_length=255)),
                ('api_url', models.CharField(blank=True, help_text='Base URL/host configuration (e.g. http://localhost:11434 for Ollama)', max_length=255)),
                ('model_name', models.CharField(default='gemini-1.5-flash', help_text='Model name identifier (e.g. gpt-4o, llama3)', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='ai_assist_a_tenant__418b57_idx')],
            },
        ),
    ]
