# Generated by Django 5.1.15 on 2026-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assist', '0003_aiinteraction_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Applied', 'Applied'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
