# Generated by Django 5.1.15 on 2026-06-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('evidence', '0001_initial'),
        ('findings', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='findings.finding'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='risk_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='assessments.riskitem'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='assessments.risktreatment'),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['tenant', 'name'], name='evidence_ev_tenant__767d29_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceversion',
            index=models.Index(fields=['document', 'version_number'], name='evidence_ev_documen_038fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceversion',
            index=models.Index(fields=['status'], name='evidence_ev_status_633562_idx'),
        ),
    ]
