# Generated by Django 5.1.15 on 2026-06-09 08:51

import django.db.models.deletion
import reporting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('ExecutiveSummary', 'Executive Summary'), ('DetailedRiskAssessment', 'Detailed Risk Assessment'), ('RiskRegister', 'Risk Register'), ('TreatmentPlan', 'Treatment Plan'), ('ChangeRequest', 'Change Request')], max_length=50)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word (DOCX)'), ('XLSX', 'Excel (XLSX)')], max_length=10)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_documents', to='assessments.assessment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to=reporting.models.tenant_report_path)),
                ('status', models.CharField(choices=[('Pending', 'Pending Scan/Generation'), ('Clean', 'Clean'), ('Infected', 'Infected'), ('Failed', 'Failed Generation')], default='Pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reporting.reportdocument')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ReportDownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_reports', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='reporting.reportversion')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportdocument',
            index=models.Index(fields=['tenant', 'assessment', 'report_type', 'file_format'], name='reporting_r_tenant__445cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportversion',
            index=models.Index(fields=['document', 'version_number'], name='reporting_r_documen_82dfd4_idx'),
        ),
        migrations.AddIndex(
            model_name='reportversion',
            index=models.Index(fields=['status'], name='reporting_r_status_9da531_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdownloadhistory',
            index=models.Index(fields=['version', 'downloaded_at'], name='reporting_r_version_fcd8da_idx'),
        ),
    ]
