# Generated by Django 5.1.15 on 2026-06-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0004_centralrisk_riskitem_central_risk_riskhistory'),
        ('findings', '0001_initial'),
        ('tenants', '0002_usertenantmembership_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('control_type', models.CharField(choices=[('Administrative', 'Administrative'), ('Technical', 'Technical'), ('Physical', 'Physical')], default='Administrative', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('effectiveness', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('NeedsImprovement', 'Needs Improvement'), ('Ineffective', 'Ineffective'), ('NotTested', 'Not Tested')], default='NotTested', max_length=50)),
                ('maturity', models.CharField(choices=[('Initial', 'Initial/Ad-hoc'), ('Repeatable', 'Repeatable'), ('Defined', 'Defined'), ('Managed', 'Managed'), ('Optimizing', 'Optimizing')], default='Initial', max_length=50)),
                ('last_tested_at', models.DateField(blank=True, null=True)),
                ('next_test_date', models.DateField(blank=True, null=True)),
                ('assessment_risks', models.ManyToManyField(blank=True, related_name='linked_controls', to='assessments.riskitem')),
                ('assessments', models.ManyToManyField(blank=True, related_name='linked_controls', to='assessments.assessment')),
                ('central_risks', models.ManyToManyField(blank=True, related_name='linked_controls', to='assessments.centralrisk')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='tenants.client')),
                ('findings', models.ManyToManyField(blank=True, related_name='linked_controls', to='findings.finding')),
                ('recommendations', models.ManyToManyField(blank=True, related_name='linked_controls', to='findings.recommendation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'client'], name='controls_co_tenant__c98855_idx'), models.Index(fields=['tenant', 'name'], name='controls_co_tenant__da4656_idx')],
            },
        ),
    ]
