# Generated by Django 5.1.15 on 2026-06-09 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0004_centralrisk_riskitem_central_risk_riskhistory'),
        ('evidence', '0002_initial'),
        ('tenants', '0002_usertenantmembership_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Data', 'Information/Data'), ('Service', 'Service'), ('People', 'People'), ('Physical', 'Physical Infrastructure')], default='Hardware', max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal'), ('Confidential', 'Confidential'), ('Restricted', 'Restricted'), ('Secret', 'Secret')], default='Internal', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('criticality', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=50)),
                ('business_function', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assessment_risks', models.ManyToManyField(blank=True, related_name='linked_assets', to='assessments.riskitem')),
                ('assessments', models.ManyToManyField(blank=True, related_name='linked_assets', to='assessments.assessment')),
                ('central_risks', models.ManyToManyField(blank=True, related_name='linked_assets', to='assessments.centralrisk')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.client')),
                ('evidence_documents', models.ManyToManyField(blank=True, related_name='linked_assets', to='evidence.evidencedocument')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'client'], name='assets_asse_tenant__3b6110_idx'), models.Index(fields=['tenant', 'name'], name='assets_asse_tenant__d5292c_idx')],
            },
        ),
    ]
