# Generated by Django 5.1.15 on 2026-06-09 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentMethodologyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assessments.assessmentmethodology')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('change_request', models.TextField(blank=True, help_text='Associated Change Request context.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('InProgress', 'In Progress'), ('UnderReview', 'Under Review'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Draft', max_length=50)),
                ('asset', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('vulnerability', models.TextField(blank=True)),
                ('existing_controls', models.TextField(blank=True)),
                ('business_process_impact', models.TextField(blank=True)),
                ('confidentiality_affected', models.BooleanField(default=False)),
                ('integrity_affected', models.BooleanField(default=False)),
                ('availability_affected', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tenants.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.assessmentmethodologyversion')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. Minor, Moderate, Major', max_length=255)),
                ('score', models.IntegerField(help_text='Severity score value (e.g. 1, 2, 3, 4, 5)')),
                ('description', models.TextField(blank=True)),
                ('financial_impact_range', models.CharField(blank=True, max_length=255)),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_criteria', to='assessments.assessmentmethodologyversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='LikelihoodCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_value', models.IntegerField(help_text='Likelihood sum value (e.g. 1, 2, 3, 4, 5, 6)')),
                ('label', models.CharField(help_text='e.g. Very Low, Low, Medium, High, Very High', max_length=255)),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likelihood_criteria', to='assessments.assessmentmethodologyversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['score_value'],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. Low, Medium, High', max_length=255)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_categories', to='assessments.assessmentmethodologyversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_location', models.CharField(max_length=255)),
                ('asset_owner', models.CharField(max_length=255)),
                ('vulnerability', models.TextField()),
                ('existing_controls', models.TextField()),
                ('confidentiality_affected', models.BooleanField(default=False)),
                ('integrity_affected', models.BooleanField(default=False)),
                ('availability_affected', models.BooleanField(default=False)),
                ('proposed_controls', models.TextField(blank=True)),
                ('additional_mitigations', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_items', to='assessments.assessment')),
                ('impact_severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_items', to='assessments.impactcriteria')),
                ('residual_impact_severity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_risk_items', to='assessments.impactcriteria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Accepted Risk', 'Accepted Risk'), ('Mitigated', 'Mitigated'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('completion_notes', models.TextField(blank=True)),
                ('risk_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='assessments.riskitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='riskitem',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_items', to='assessments.threat'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_assessments', to='assessments.threat'),
        ),
        migrations.CreateModel(
            name='ThreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='threat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='assessments.threatcategory'),
        ),
        migrations.CreateModel(
            name='ThreatFrequencyCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('score', models.IntegerField(help_text='Frequency score value (e.g. 1, 2, 3)')),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_criteria', to='assessments.assessmentmethodologyversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.AddField(
            model_name='riskitem',
            name='residual_threat_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_risk_items', to='assessments.threatfrequencycriteria'),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='threat_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_items', to='assessments.threatfrequencycriteria'),
        ),
        migrations.CreateModel(
            name='VulnerabilityProbabilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('score', models.IntegerField(help_text='Probability score value (e.g. 1, 2, 3)')),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probability_criteria', to='assessments.assessmentmethodologyversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.AddField(
            model_name='riskitem',
            name='residual_vulnerability_probability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_risk_items', to='assessments.vulnerabilityprobabilitycriteria'),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='vulnerability_probability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_items', to='assessments.vulnerabilityprobabilitycriteria'),
        ),
        migrations.AddIndex(
            model_name='assessmentmethodology',
            index=models.Index(fields=['tenant', 'name'], name='assessments_tenant__c3fb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentmethodologyversion',
            index=models.Index(fields=['tenant', 'methodology', 'version_number'], name='assessments_tenant__352353_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentmethodologyversion',
            unique_together={('methodology', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='likelihoodcriteria',
            unique_together={('methodology_version', 'score_value')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['tenant', 'client', 'status'], name='assessments_tenant__229e82_idx'),
        ),
    ]
