# Generated by Django 5.1.15 on 2026-06-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('evidence', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0, help_text='Compliance weight score for this choice selection.')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=50)),
                ('is_latest', models.BooleanField(default=True)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='assessments.assessmenttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('InProgress', 'In Progress'), ('UnderReview', 'Under Review'), ('Completed', 'Completed')], default='Draft', max_length=50)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('compliance_rating', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assessments', to='tenants.client')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.assessmenttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True)),
                ('guidance_notes', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('Text', 'Short Text'), ('LongText', 'Long Text / TextArea'), ('Dropdown', 'Single-Select Dropdown'), ('MultiSelect', 'Multi-Select Checkboxes'), ('Radio', 'Radio Buttons'), ('Date', 'Date Selector'), ('Numeric', 'Numeric Input'), ('Evidence', 'Evidence File Upload Required')], default='Text', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('attached_evidence', models.ManyToManyField(blank=True, to='evidence.evidencedocument')),
                ('selected_choices', models.ManyToManyField(blank=True, to='assessments.questionchoice')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.templateassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.templatequestion')),
            ],
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.templatequestion'),
        ),
        migrations.CreateModel(
            name='TemplateScoringRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. Highly Compliant, Unacceptable Risk', max_length=100)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('color', models.CharField(default='success', help_text='Bootstrap contextual class name (success, warning, danger).', max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_ranges', to='assessments.assessmenttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessmenttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.templatesection'),
        ),
        migrations.AddIndex(
            model_name='assessmenttemplate',
            index=models.Index(fields=['tenant', 'name', 'is_latest'], name='assessments_tenant__275512_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassessment',
            index=models.Index(fields=['tenant', 'client', 'status'], name='assessments_tenant__3d1204_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateanswer',
            unique_together={('assessment', 'question')},
        ),
        migrations.AddIndex(
            model_name='questionchoice',
            index=models.Index(fields=['question', 'order'], name='assessments_questio_47904f_idx'),
        ),
        migrations.AddIndex(
            model_name='templatesection',
            index=models.Index(fields=['template', 'order'], name='assessments_templat_f908d6_idx'),
        ),
        migrations.AddIndex(
            model_name='templatequestion',
            index=models.Index(fields=['section', 'order'], name='assessments_section_724997_idx'),
        ),
    ]
