# Generated by Django 5.1.15 on 2026-06-09 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_assessor_templateassessment_assessor'),
        ('tenants', '0002_usertenantmembership_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_location', models.CharField(blank=True, max_length=255)),
                ('asset_owner', models.CharField(blank=True, max_length=255)),
                ('vulnerability', models.TextField()),
                ('existing_controls', models.TextField(blank=True)),
                ('confidentiality_affected', models.BooleanField(default=False)),
                ('integrity_affected', models.BooleanField(default=False)),
                ('availability_affected', models.BooleanField(default=False)),
                ('proposed_controls', models.TextField(blank=True)),
                ('additional_mitigations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Under Review', 'Under Review'), ('Mitigated', 'Mitigated'), ('Accepted', 'Accepted'), ('Archived', 'Archived')], default='Draft', max_length=50)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_status', models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Expired', 'Expired'), ('Rejected', 'Rejected')], default='None', max_length=50)),
                ('acceptance_rationale', models.TextField(blank=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('acceptance_expiry', models.DateField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_risks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_risks', to='tenants.client')),
                ('impact_severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='central_risks', to='assessments.impactcriteria')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('residual_impact_severity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_central_risks', to='assessments.impactcriteria')),
                ('residual_threat_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_central_risks', to='assessments.threatfrequencycriteria')),
                ('residual_vulnerability_probability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_central_risks', to='assessments.vulnerabilityprobabilitycriteria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_risks', to='assessments.threat')),
                ('threat_frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='central_risks', to='assessments.threatfrequencycriteria')),
                ('vulnerability_probability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='central_risks', to='assessments.vulnerabilityprobabilitycriteria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='riskitem',
            name='central_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_items', to='assessments.centralrisk'),
        ),
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='assessments.centralrisk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
