# Generated by Django 5.1.15 on 2026-06-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenantmembership',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='tenants.client'),
        ),
        migrations.AlterField(
            model_name='usertenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('assessor', 'Assessor'), ('reviewer', 'Reviewer'), ('client', 'Client'), ('viewer', 'Viewer')], default='viewer', max_length=50),
        ),
    ]
