# Generated by Django 5.1.15 on 2026-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_usertenantmembership_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='m365_auto_create_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='m365_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='m365_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='m365_default_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('assessor', 'Assessor'), ('reviewer', 'Reviewer'), ('client', 'Client'), ('viewer', 'Viewer')], default='viewer', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='m365_sso_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
